<?php

namespace AppBundle\Repository;

/**
 * EssaiDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EssaiDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
