<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LibCim10Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibCim10Repository extends EntityRepository
{
}
