<?php

namespace AppBundle\Repository;

/**
 * LibCim10Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibCim10Repository extends \Doctrine\ORM\EntityRepository
{
}
