<?php

namespace AppBundle\Repository;

/**
 * ValidationErreurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidationErreurRepository extends \Doctrine\ORM\EntityRepository
{
}
