<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Visite;
use Doctrine\ORM\QueryBuilder;

/**
 * VisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * @param QueryBuilder $queryBuilder
     * @param User $user
     * @return QueryBuilder
     */
    private function joinUserWhereUser(QueryBuilder $queryBuilder, User $user)
    {
        $queryBuilder->leftJoin('v.inclusion', 'i')
            ->leftJoin('i.arc', 'a')
            ->leftJoin('i.essai', 'e')
            ->leftJoin('i.patient', 'p');

        if (!$user->getEssais()->isEmpty() || $user->getRulesProtocole() == User::NO_PROTOCOLE) {
            $queryBuilder->andWhere("u = :user")
                ->setParameter("user", $user)
                ->leftJoin('e.users', 'u');

        }

        return $queryBuilder;
    }


    /**
     * @param User $user
     * @param $search
     * @param $searchId
     * @return \Doctrine\ORM\Query
     */
    public function getQuery(User $user, $search, $searchId)
    {
        $queryBuilder = $this->createQueryBuilder('v')
            ->where("v.id like :search or p.nom like :search or p.prenom like :search or e.nom like :search or v.date like :search or v.statut like :search or v.type like :search or v.calendar like :search or v.id = :searchId")
            ->addSelect("e","a","p","i")
            ->groupBy('v.id')
            ->setParameter('searchId', $searchId)
            ->setParameter('search', '%' . $search . '%');

        $queryBuilder = $this->joinUserWhereUser($queryBuilder, $user);

        return $queryBuilder->getQuery();
    }

    /**
     * @param \DateTime|null $debut
     * @param \DateTime|null $fin
     * @return array
     */
    public function findByDate(?\DateTime $debut, ?\DateTime $fin = null)
    {
        if ($fin == null) {
            $fin = date("Y-m-d H:i:s");
        }

        $queryBuilder = $this->createQueryBuilder('v')
            ->where('v.date >= :debut')
            ->andWhere('v.date <= :fin')
            ->setParameter('debut', $debut)
            ->setParameter('fin', $fin);

        return $queryBuilder->getQuery()->getResult();
    }

    /**
     * @return array
     */
    public function findToday()
    {
        $debut = (new \DateTime())->setTime(0, 0);
        $fin = (new \DateTime())->setTime(23, 59);

        $queryBuilder = $this->createQueryBuilder('v')
            ->where('v.date >= :debut')
            ->andWhere('v.date <= :fin')
            ->setParameter('debut', $debut)
            ->setParameter('fin', $fin);

        return $queryBuilder->getQuery()->getResult();
    }

    /**
     * @param $user
     * @return Visite[]
     * @throws \Exception
     */
    public function findForAWeek(User $user)
    {
        $debut = (new \DateTime())->setTime(0, 0);
        $now = (new \DateTime())->setTime(0, 0);
        $interval = new \DateInterval('P1W');
        $fin = $now->add($interval);


        $queryBuilder = $this->createQueryBuilder('v')
            ->addSelect("e", "a", "i","p")
            ->where('v.date >= :debut')
            ->andWhere('v.date <= :fin')
            ->setParameter('debut', $debut)
            ->setParameter('fin', $fin)
            ->orderBy('v.date', "ASC");

        $queryBuilder = $this->joinUserWhereUser($queryBuilder, $user);

        return $queryBuilder->getQuery()->getResult();
    }

    public function findConfirmeeTheoriqueDepassee($user)
    {
        $queryBuilder = $this->createQueryBuilder('v')
            ->addSelect("e", "a", "i","p")
            ->andWhere('v.date < :today')
            ->andWhere("v.statut = '". Visite::PREVUE_CONFIRMEE ."' or v.statut = '". Visite::PREVUE_THEORIQUE ."'")
            ->setParameter('today', new \DateTime("today"))
            ->orderBy('v.date', "ASC");

        $queryBuilder = $this->joinUserWhereUser($queryBuilder, $user);

        return $queryBuilder->getQuery()->getResult();
    }

    /**
     * @param null $date
     * @param $filters
     * @param User $user
     * @return array
     */
    public function findAdvancedArray($date = null, $filters, User $user)
    {
        $queryBuilder = $this->createQueryBuilder('v')
            ->addSelect('p', 'a', 'e', 'i')
            ->groupBy("v.id")
            ->setMaxResults(500);

        $queryBuilder = $this->joinUserWhereUser($queryBuilder, $user);


        /** @var \DateTime $date */
        if ($date) {
            $queryBuilder->andWhere("YEAR(v.date) = :year")
                ->setParameter("year", $date->format("Y"))
                ->andWhere("MONTH(v.date) = :month")
                ->setParameter("month", $date->format("m") )
                ->andWhere("DAY(v.date) = :day")
                ->setParameter("day", $date->format("d") );
        }


        if (isset($filters["statut"]) && $filters["statut"] != null) {
            $queryBuilder->andWhere("v.statut = :statut")
                ->setParameter("statut", $filters["statut"]);
        }

        $queryBuilder->orderBy('v.date', 'ASC');

        return $queryBuilder->getQuery()->getArrayResult();
    }
}
